version: 0.2

env:
  variables:
    REPO: "sr79979"
    PROJECTS: "youtube-clone band-booking"
    BUILD_NUMBER: "latest"  # You can override this via CodeBuild environment variables

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo "Installing Trivy via binary..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - trivy --version
      - echo "🔧 Setting JAVA_HOME..."
      - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      - echo "JAVA_HOME is set to $JAVA_HOME"

      - echo "📦 Installing Maven..."
      - curl -fsSL https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz -o maven.tar.gz
      - tar -xzf maven.tar.gz
      - mv apache-maven-3.9.11 /opt/maven
      - export MAVEN_HOME=/opt/maven
      - export PATH=$MAVEN_HOME/bin:$PATH
      - mvn -v
  # pre_build:
  #   commands:
  #     - echo "Detecting changed projects..."
  #     - git fetch --unshallow || true
  #     - |
  #       bash -c '
  #       CHANGED=()
  #       for project in $PROJECTS; do
  #         if git diff --name-only origin/main HEAD | grep "^$project/"; then
  #           CHANGED+=("$project")
  #         fi
  #       done
  #       echo "Changed projects: ${CHANGED[*]}"
  #       echo "${CHANGED[*]}" > changed_projects.txt
  #       '
        
  build:
    commands:
      - echo "Building Docker images..."
      - cd band-booking
      - mvn clean package
  # post_build:
  #   commands:
  #     - echo "Scanning Docker images..."
  #     - mkdir -p scan_reports
  #     - for project in $changed_projects; do
  #         trivy image --format table --input $project.tar --output scan_reports/scan_$project.md || true;
  #         grep -E 'Total:|HIGH:|CRITICAL:' scan_reports/scan_$project.md > scan_reports/scan_summary_$project.md || echo "No vulnerabilities found!" > scan_reports/scan_summary_$project.md;
  #       done

artifacts:
  files:
    - '*.tar'
    - 'scan_reports/*'
    # - 'changed_projects.txt'
  discard-paths: no